# Generated by Django 5.2.1 on 2025-05-12 15:03

import datetime
import django.core.validators
import django.db.models.deletion
import racing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=96)),
                ('last_name', models.CharField(max_length=96)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2000, 12, 31))])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=256, unique=True)),
                ('city', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('logo_image', models.ImageField(upload_to='TeamLogos', validators=[racing.models.check_logo_size])),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=256, unique=True)),
                ('city', models.CharField(max_length=18)),
                ('country', models.CharField(max_length=18)),
                ('race_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 5, 12))])),
                ('registration_closure_date', models.DateField(blank=True, null=True)),
                ('driver', models.ManyToManyField(blank=True, related_name='races', to='racing.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='racing.team'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_driver_name'),
        ),
    ]
