# Generated by Django 5.2.1 on 2025-05-13 14:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 5, 13))]),
        ),
    ]
