# Generated by Django 5.2.1 on 2025-05-14 07:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_alter_race_race_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 5, 14))]),
        ),
    ]
