# Generated by Django 5.2.1 on 2025-05-19 14:06

import datetime
import django.core.validators
import racing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0003_alter_race_race_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 5, 19))]),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_image',
            field=models.ImageField(upload_to='TeamLogos/', validators=[racing.models.check_logo_size]),
        ),
    ]
